/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BSCBridge } from "./BSCBridge";

export { BSCBridge__factory } from "./factories/BSCBridge__factory";
